#pragma once
#include "obse64_common/obse64_version.h"
#include "obse64_common/Log.h"
#include "obse64_common/Errors.h"
#include "IVersionCheck.h"

#define PLUGIN_AUTHOR				"obr_quest_companion"
#define PLUGIN_NAME_SHORT			"obr_quest_companion"	
#define PLUGIN_NAME_LONG			"obr_quest_companion"	
#define PLUGIN_VERSION_MAJOR		1
#define PLUGIN_VERSION_MINOR		0
#define PLUGIN_VERSION_BUILD		0
#define SDK_VERSION_STRING			VERSION_TO_STRING(OBSE_VERSION_INTEGER, OBSE_VERSION_INTEGER_MINOR, OBSE_VERSION_INTEGER_BETA)
#define PLUGIN_VERSION_STRING		VERSION_TO_STRING(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_BUILD)
#define PLUGIN_VERSION_DLL			MAKE_EXE_VERSION(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_BUILD)
#define PLUGIN_VERSION_INFO			PLUGIN_NAME_SHORT " v%s (0x%08X) (SDK v%s)", PLUGIN_VERSION_STRING, PLUGIN_VERSION_DLL, SDK_VERSION_STRING
#define MINIMUM_RUNTIME_VERSION		RUNTIME_VERSION_0_411_140
#define SUPPORTED_RUNTIME_VERSION	RUNTIME_VERSION
#define SUPPORTED_RUNTIME_VERSION_STRICT	false
#define COMPATIBLE(runtimeVersion)			(runtimeVersion == SUPPORTED_RUNTIME_VERSION)
